language: perl
perl:
  - "5.22"
  - "5.24.3"
  - "5.26"

matrix:
  fast_finish: true
  allow_failures:
    - env: USE_CPANFILE_SNAPSHOT=false CPAN_RESOLVER=metadb PERL_CARTON_PATH=$TRAVIS_BUILD_DIR/no-snapshot HARNESS_VERBOSE=1
    - env: USE_CPANFILE_SNAPSHOT=true COVERAGE=1
env:
  global:
    # Carton --deployment only works on the same version of perl
    # that the snapshot was built from.
    - DEPLOYMENT_PERL_VERSION=5.22
    - DEVEL_COVER_OPTIONS="-ignore,^local/"
    - PERL_CARTON_PATH=$TRAVIS_BUILD_DIR/local
    - CPAN_RESOLVER=snapshot
  matrix:

    # Get one passing run with coverage and one passing run with Test::Vars
    # checks.  If run together they more than double the build time.
    - USE_CPANFILE_SNAPSHOT=false CPAN_RESOLVER=metadb PERL_CARTON_PATH=$TRAVIS_BUILD_DIR/no-snapshot HARNESS_VERBOSE=1
    - USE_CPANFILE_SNAPSHOT=true
    - USE_CPANFILE_SNAPSHOT=true COVERAGE=1

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init

  - npm install -g less js-beautify
  # Pre-install from backpan to avoid upgrade breakage.
  - cpanm -n http://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/common-sense-3.6.tar.gz
  - cpanm -n App::cpm Carton

install:
  - cpan-install --coverage   # installs converage prereqs, if enabled
  - cpm install -L $PERL_CARTON_PATH --resolver $CPAN_RESOLVER

before_script:
  - coverage-setup

script:
  # Parallel tests seem to have Heisenfailures.  Disable for now.
  # - carton exec prove -lr -j$(test-jobs) t
  - carton exec prove -lr t

after_success:
  - coverage-report

notifications:
  email:
    recipients:
      - olaf@wundersolutions.com
    on_success: change
    on_failure: always
  irc: "irc.perl.org#metacpan-travis"

# Use newer travis infrastructure.
sudo: false
cache:
  directories:
    - local
